= dechat_es8

image:https://travis-ci.org/Arquisoft/dechat_es8.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es8"]
image:https://codecov.io/gh/Arquisoft/dechat_es8/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es8"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es8?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es8&utm_campaign=Badge_Grade"]

== Autor

Cristian Lado González

== Documentación

La documentación está hecha en http://asciidoc.org/[AsciiDoc]
usando las plantillas https://arc42.org/[arc42] .
Los documentos se encuentran en
 https://github.com/Arquisoft/dechat_es8/tree/master/adocs[adocs].

Para generar la documentación hay que instalar gulp:

----
npm install gulp
----

Una vez instalado solo hace falta el siguiente comando:

----
gulp
----

== Compilar y ejecutar

Para ejecutar la aplicación se puede instalar http-server:

----
 npm install http-server -g
----

Cuando se realicen cambios en el código se debe ejecutar el siguiente comando para generar la aplicación:

----
 npm run build:web
----

Por último, ejecuta:

----
http-server ./src
----

Este último comando dará algunas direcciones IP donde estará disponible la aplicación.

== Test

Hay algunas pruebas unitarias en:
 https://github.com/Arquisoft/dechat_es8/tree/master/test[test].

También hay algunas BDD realizadas con
 https://cucumber.io/[Cucumber].

Para lanzar los tests de integración continua se debe realizar:

----
npm test
----

Para probar las historias de usuario con Cucumber se debe realizar:

----
npm run cucumber
----

Por último existen pruebas de carga realizadas con
 https://gatling.io/[Gatling].
Los resultados de estas pruebas están en https://github.com/Arquisoft/dechat_es8/tree/master/gatling[gatling].
